[project]
name = "workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "S-Astralcoder", email = "suraj.astralcode.ai@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
workflow = "workflow:main"

[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"
