[workflow]
name = "initial structure"
workspace = "./workspace/testspace" # after specifying the workspace. the following paths can be written relative the given working directory
force = false
dry_run = true
allow = false
show = true


# for optional parameter leaving it undefined will result in automatically considering as false

[[actions]] 
operation = "create"
type = "folder"
path = "./src"

[[actions]]
operation = "create"
type = "file"
path = "./src/test/__init__.py"
recursive = true

[[actions]]
operation = "create"
type = "folder"
path = "./src/test/my"
recursive = true

[[actions]]
operation = "create"
type = "folder"
path = "./src/to/do"
recursive = true

[[actions]]
operation = "copy"
source_path = "./src/test/__init__.py"
destination_path = "."


